<a href="https://colab.research.google.com/github/VighneshAlevoor/DeepLearning/blob/master/ANN_PreTuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("Churn_Modelling.csv")
data

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [3]:
x=data.iloc[:,3:-1].values
y=data.iloc[:,-1:].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [5]:
label1=LabelEncoder()
x[:,1]=label1.fit_transform(x[:,1])
label2=LabelEncoder()
x[:,2]=label2.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [6]:
colT=ColumnTransformer([('Encoding',OneHotEncoder(),[1])], remainder='passthrough')
x=colT.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
x=x[:,1:]
x.shape

(10000, 11)

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [0]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [14]:
classifier=Sequential()

In [15]:
#adding input layer and first hidden layer
classifier.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11))      
#output_dim - hidden layer: can do parameter tuning else we can take avg of input layer+output layer
#init - assigns weights randomly in small values
#activation - rectifier for hidden (standard in most cases) and sigmoid for output

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [16]:
#adding second hidden layer, no need input_dim since already given above
classifier.add(Dense(output_dim=6, init='uniform', activation='relu')) 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [17]:
classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))
#if we have more than 2 outputs: use softmax as activation

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [19]:
classifier.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
#adam is type of stochastic gradient descent optimizer
#metrics expects a list hence []



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [20]:
#fitting ANN to the training set
classifier.fit(x_train,y_train,batch_size=10 ,epochs=100)





Epoch 1/100





8000/8000 [==============================] - 2s 190us/step - loss: 0.4814 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4278 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4213 - acc: 0.8054
Epoch 4/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4182 - acc: 0.8242
Epoch 5/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4157 - acc: 0.8282
Epoch 6/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4145 - acc: 0.8302
Epoch 7/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4131 - acc: 0.8325
Epoch 8/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4118 - acc: 0.8316
Epoch 9/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4109 - acc: 0.8331
Epoch 10/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4095 - acc

In [21]:
y_pred=classifier.predict(x_test)
y_pred

array([[0.18221673],
       [0.31293958],
       [0.18196106],
       ...,
       [0.1502833 ],
       [0.12184915],
       [0.09708941]], dtype=float32)

In [25]:
y_pred=(y_pred >0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1549,   46],
       [ 269,  136]])

In [27]:
score=accuracy_score(y_test,y_pred)
score

0.8425

In [0]:
#Predict below:Geography: France Credit Score: 600 Gender: Male Age: 40 years old Tenure: 3 years Balance: $60000 Number of Products: 2
#Does this customer have a credit card ? Yes Is this customer an Active Member: Yes Estimated Salary: $50000

new_pred=classifier.predict(scaler.transform(np.array([[0,0,600, 1, 40,3,60000,2,1,1,50000]])))
new_pred=(new_pred>0.5)
#[[]] double brackets to have as 2d array and first row of that 2d array

In [33]:
new_pred

array([[False]])